/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle.learn;

public class Library {
    public boolean someLibraryMethod() {
        System.out.print("Library");
        return true;
    }
}
